"""initial schema

Revision ID: c7a64f20c58a
Revises: 
Create Date: 2026-08-07 20:41:00.720178

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'c7a64f20c58a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_stripe_customer_id'), 'customer', ['stripe_customer_id'], unique=False)
    op.create_table('apikey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_customer_id'), 'apikey', ['customer_id'], unique=False)
    op.create_index(op.f('ix_apikey_prefix'), 'apikey', ['prefix'], unique=False)
    op.create_table('monitor',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('next_check_at', sa.DateTime(), nullable=False),
    sa.Column('last_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_customer_id'), 'monitor', ['customer_id'], unique=False)
    op.create_index(op.f('ix_monitor_next_check_at'), 'monitor', ['next_check_at'], unique=False)
    op.create_table('usageevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marketplace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('cost_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usageevent_created_at'), 'usageevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_usageevent_customer_id'), 'usageevent', ['customer_id'], unique=False)
    op.create_table('monitorevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monitor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('previous_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitorevent_created_at'), 'monitorevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_monitorevent_monitor_id'), 'monitorevent', ['monitor_id'], unique=False)
    op.create_table('webhookdelivery',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monitor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhookdelivery_created_at'), 'webhookdelivery', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhookdelivery_monitor_id'), 'webhookdelivery', ['monitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhookdelivery_monitor_id'), table_name='webhookdelivery')
    op.drop_index(op.f('ix_webhookdelivery_created_at'), table_name='webhookdelivery')
    op.drop_table('webhookdelivery')
    op.drop_index(op.f('ix_monitorevent_monitor_id'), table_name='monitorevent')
    op.drop_index(op.f('ix_monitorevent_created_at'), table_name='monitorevent')
    op.drop_table('monitorevent')
    op.drop_index(op.f('ix_usageevent_customer_id'), table_name='usageevent')
    op.drop_index(op.f('ix_usageevent_created_at'), table_name='usageevent')
    op.drop_table('usageevent')
    op.drop_index(op.f('ix_monitor_next_check_at'), table_name='monitor')
    op.drop_index(op.f('ix_monitor_customer_id'), table_name='monitor')
    op.drop_table('monitor')
    op.drop_index(op.f('ix_apikey_prefix'), table_name='apikey')
    op.drop_index(op.f('ix_apikey_customer_id'), table_name='apikey')
    op.drop_table('apikey')
    op.drop_index(op.f('ix_customer_stripe_customer_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
